# Generated by Django 5.0 on 2023-12-25 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('owner_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='media/public/uploads/audioclip')),
                ('random', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='robotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('port', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/public/uploads.images/robot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=True)),
            ],
        ),
    ]
