# Generated by Django 5.0 on 2024-01-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_goalsmodel_own'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalsmodel',
            name='own',
        ),
    ]
