# Generated by Django 5.0 on 2024-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_alter_goalsmodel_audio_alter_robotmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsmodel',
            name='audio',
            field=models.FileField(upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='robotmodel',
            name='image',
            field=models.ImageField(upload_to='uploads/images/profile/'),
        ),
    ]
