# Generated by Django 5.0 on 2024-01-09 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0012_alter_robotmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=5)),
            ],
        ),
    ]
