# Generated by Django 5.0 on 2024-01-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0013_locationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locationModel',
        ),
    ]
