# Generated by Django 5.0 on 2024-01-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(upload_to='uploads/images/profile/'),
        ),
        migrations.AlterField(
            model_name='productsmodels',
            name='image',
            field=models.ImageField(upload_to='uploads/images/products/'),
        ),
    ]
