# Generated by Django 5.0 on 2024-01-09 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_customuser_profile_alter_productsmodels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=6)),
            ],
        ),
    ]
