# Generated by Django 5.0 on 2024-01-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_loactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loactionmodel',
            name='owner_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
