# Generated by Django 5.0 on 2024-01-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_loactionmodel_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1)),
                ('comment', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
            ],
        ),
    ]
