# Generated by Django 5.0 on 2024-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
