# Generated by Django 5.0 on 2023-12-25 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loops',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roboid', models.CharField(max_length=100)),
                ('goalid', models.CharField(max_length=100)),
                ('time_delay_seconds', models.IntegerField()),
                ('admin_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='loopevent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=100)),
                ('goalid', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='loops.loops')),
            ],
        ),
    ]
