# Generated by Django 5.0 on 2023-12-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loopevent',
            old_name='event_id',
            new_name='unique_id',
        ),
        migrations.RemoveField(
            model_name='loopevent',
            name='loop',
        ),
        migrations.RemoveField(
            model_name='loops',
            name='goalid',
        ),
    ]
