# Generated by Django 5.0 on 2023-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0002_rename_event_id_loopevent_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loops',
            name='timestring',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
