# Generated by Django 5.0 on 2023-12-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0003_loops_timestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loops',
            name='timestring',
            field=models.CharField(max_length=100),
        ),
    ]
