# Generated by Django 5.0 on 2023-12-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0005_alter_loops_time_delay_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loops',
            name='timestring',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
