# Generated by Django 5.0 on 2023-12-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('encoding', models.JSONField()),
                ('image_path', models.CharField(max_length=255)),
                ('encodings_file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
